"""Alembic environment.

The database URL comes from application settings, not alembic.ini, so migrations
always target the same database the app does.
"""
from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.config import get_settings  # noqa: E402
from app.db.base import Base  # noqa: E402
import app.models  # noqa: E402,F401  (registers every table on Base.metadata)

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.database_url)

target_metadata = Base.metadata


def _include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Hide PostgreSQL-only objects when autogenerating against another backend.

    The GIN indexes on JSONB columns are declared with ``ddl_if(dialect=...)`` and
    are genuinely absent from the SQLite dev database. Without this filter,
    ``alembic check`` reports permanent phantom drift on SQLite and every new
    autogenerated revision tries to re-add them.
    """
    if type_ == "index":
        using = obj.dialect_options.get("postgresql", {}).get("using")
        if using == "gin" and not settings.is_postgres:
            return False
    return True


def _common_kwargs() -> dict:
    return {
        "target_metadata": target_metadata,
        "compare_type": True,
        "compare_server_default": True,
        "include_object": _include_object,
        # SQLite cannot ALTER most columns; batch mode rewrites the table instead.
        # Harmless on PostgreSQL, essential for the local dev database.
        "render_as_batch": settings.database_url.startswith("sqlite"),
    }


def run_migrations_offline() -> None:
    context.configure(
        url=settings.database_url, literal_binds=True,
        dialect_opts={"paramstyle": "named"}, **_common_kwargs(),
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.", poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, **_common_kwargs())
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
