"""initial schema

Revision ID: 62974324bec9
Revises: 
Create Date: 2026-08-18 00:19:14.036342
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '62974324bec9'
down_revision = None
branch_labels = None
depends_on = None


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def _create_gin_index(name: str, table: str, columns: list[str]) -> None:
    """Create a GIN index, but only on PostgreSQL.

    SQLite has no GIN access method. Autogenerate cannot carry the model's
    ``ddl_if(dialect="postgresql")`` gate into the migration, so the gate is
    reapplied here - otherwise the dev database would grow two plain B-tree
    indexes that serve no purpose and misrepresent the production schema.
    """
    if _is_postgres():
        op.create_index(name, table, columns, unique=False, postgresql_using="gin")


def _drop_gin_index(name: str, table: str) -> None:
    if _is_postgres():
        op.drop_index(name, table_name=table)



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upc', sa.String(length=14), nullable=True),
    sa.Column('normalized_name', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=320), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('normalized_brand', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=96), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_normalized_name', ['normalized_name'], unique=False)
        batch_op.create_index('ix_products_upc', ['upc'], unique=False)
    _create_gin_index('ix_products_attributes_gin', 'products', ['attributes'])

    op.create_table('retailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('supports_online_pricing', sa.Boolean(), nullable=False),
    sa.Column('requires_membership', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('zip', sa.String(length=10), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('retailer_sku', sa.String(length=96), nullable=False),
    sa.Column('upc', sa.String(length=14), nullable=True),
    sa.Column('display_name', sa.String(length=320), nullable=False),
    sa.Column('size_text', sa.String(length=96), nullable=True),
    sa.Column('pack_count', sa.Integer(), nullable=False),
    sa.Column('net_content_value', sa.Float(), nullable=True),
    sa.Column('net_content_uom', sa.String(length=16), nullable=True),
    sa.Column('base_quantity', sa.Float(), nullable=True),
    sa.Column('base_uom', sa.String(length=8), nullable=True),
    sa.Column('uom_kind', sa.String(length=16), nullable=True),
    sa.Column('is_organic', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'retailer_sku', name='uq_variant_retailer_sku')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index('ix_variants_product', ['product_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('store_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_primary_for_zip', sa.Boolean(), nullable=False),
    sa.Column('address_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'store_number', name='uq_store_retailer_number')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index('ix_stores_zip', ['zip'], unique=False)

    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Float(), nullable=True),
    sa.Column('unit_price_uom', sa.String(length=16), nullable=True),
    sa.Column('promotion_type', sa.String(length=32), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.create_index('ix_observations_variant_store_time', ['variant_id', 'store_id', 'observed_at'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('regular_price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit_price_cents', sa.Float(), nullable=True),
    sa.Column('unit_price_uom', sa.String(length=16), nullable=True),
    sa.Column('promotion_type', sa.String(length=32), nullable=False),
    sa.Column('promotion_text', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('is_verified_in_store', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'store_id', name='uq_price_variant_store')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index('ix_prices_observed_at', ['observed_at'], unique=False)
        batch_op.create_index('ix_prices_store', ['store_id'], unique=False)

    op.create_table('product_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left_variant_id', sa.Integer(), nullable=False),
    sa.Column('right_variant_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vetoed', sa.Boolean(), nullable=False),
    sa.Column('veto_reason', sa.Text(), nullable=True),
    sa.Column('human_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['left_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('left_variant_id', 'right_variant_id', name='uq_match_pair')
    )
    with op.batch_alter_table('product_matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_confidence', ['confidence'], unique=False)
        batch_op.create_index('ix_matches_left', ['left_variant_id'], unique=False)
    _create_gin_index('ix_matches_signals_gin', 'product_matches', ['signals'])

    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.create_index('ix_list_items_list', ['shopping_list_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.drop_index('ix_list_items_list')

    op.drop_table('shopping_list_items')
    _drop_gin_index('ix_matches_signals_gin', 'product_matches')
    with op.batch_alter_table('product_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_left')
        batch_op.drop_index('ix_matches_confidence')

    op.drop_table('product_matches')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index('ix_prices_store')
        batch_op.drop_index('ix_prices_observed_at')

    op.drop_table('prices')
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_observations_variant_store_time')

    op.drop_table('price_observations')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index('ix_stores_zip')

    op.drop_table('stores')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_variants_product')

    op.drop_table('product_variants')
    op.drop_table('shopping_lists')
    op.drop_table('retailers')
    _drop_gin_index('ix_products_attributes_gin', 'products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_upc')
        batch_op.drop_index('ix_products_normalized_name')

    op.drop_table('products')
    # ### end Alembic commands ###
